export * from './IArray'
export * from './IDeque'
export * from './IHash'
export * from './IHeap'
export * from './ILinkedList'
export * from './IQueue'
export * from './IStack'
export * from './ITree'
